# Generated by Django 5.0.6 on 2024-07-14 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=300)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_oferta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(null=True, upload_to='categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paginapp.producto')),
                ('image', models.ImageField(upload_to='bicicletas')),
            ],
            options={
                'verbose_name': 'bicicleta',
                'verbose_name_plural': 'bicicletas',
            },
            bases=('paginapp.producto',),
        ),
        migrations.CreateModel(
            name='Freno',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paginapp.producto')),
                ('image', models.ImageField(upload_to='frenos')),
            ],
            options={
                'verbose_name': 'freno',
                'verbose_name_plural': 'frenos',
            },
            bases=('paginapp.producto',),
        ),
        migrations.CreateModel(
            name='Neumatico',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paginapp.producto')),
                ('image', models.ImageField(upload_to='neumaticos')),
            ],
            options={
                'verbose_name': 'neumático',
                'verbose_name_plural': 'neumáticos',
            },
            bases=('paginapp.producto',),
        ),
    ]
